# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.5.1
pipelines:
  default:
    - step:
        caches:
          - bundler
          - pip
        script:
          - apt-get update && apt-get install -y python-dev
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install awsebcli --upgrade
          - pip install awscli --upgrade
          - bundle install --path vendor/bundle
          - bundle exec rake
          - aws --version
          - eb init Bookmaker -r us-east-1 -p arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.5 running on 64bit Amazon Linux/2.8.6
          - eb deploy Bookmaker-production
        services:
          - postgres
definitions:
  caches:
    bundler: vendor/bundle
    pip: ~/.cache/pip
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'bookmaker-test'
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'bookmaker-test'
